name = "rudo_ai_poc"
main = "src/index.ts"
compatibility_date = "2024-10-28"
compatibility_flags = [ "nodejs_compat" ]

assets = { directory = "public" }

[vars]
OPEN_AI_KEY = ""

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "rudo-ai-poc"
database_id = "e78aaf30-2c5b-41bc-b1f2-66c2381755a4"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1